#!/bin/bash
LC_ALL=C

# Check branch name is valid

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^([0-9]+\/+)[A-z0-9_ +-]+$"

message="The branch name $local_branch does not meet the naming convertion of the format: TicketNumber/name of branch. Here is an example 12/Git Hooks Challenge. The commit will be rejected."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

# Clear all outputs from all jupyter notebooks

for file in *.ipynb
do
    echo "Removing output from notebook $file"
    jupyter nbconvert --clear-output --inplace $file
done

exit 0